---
- name: Install Teamviewer from remote source
  become: true
  apt:
    deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  when: '"Microsoft" not in ansible_facts["kernel"]'
