---
- name: Install Google Chrome from remote source
  become: true
  apt:
    # yamllint disable-line rule:line-length
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_{{ machine_architecture }}.deb
