---
- name: Install kustomize
  include_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: kustomize
    url: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/{{ tooling.version.kustomize }}/kustomize_{{ tooling.version.kustomize }}_linux_amd64.tar.gz"
    version: "{{ tooling.version.kustomize }}"
    unzip: true


