---
- name: Install op (1Password CLI)
  include_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: op
    url: "https://cache.agilebits.com/dist/1P/op2/pkg/{{ tooling.version.onepassword }}/op_linux_amd64_{{ tooling.version.onepassword }}.zip"
    version: "{{ tooling.version.onepassword }}"
    unzip: true


