---
- name: Install pandoc from remote source
  become: true
  apt:
    # yamllint disable-line rule:line-length
    deb: https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-{{ machine_architecture }}.deb
