#!/usr/bin/env bash

usage() {
    cat << USAGE
Description:
  Shorthand script to start the ansible provisioning playbook with different
  tags. By default it will run the full provisioning suite.
  example usage:
    ./dev-provision -i provisioning/inventory_custom_example.yml

Usage:
  dev-provision [configuration]

Available configurations
  dotfiles   only provision dotfiles
  packages   only provision system packages
  tooling    only provision tooling

Flags:
  -h, --help         shows this help message
  -i, --inventory    path to an inventory file
USAGE
}

setup() {
  echo ">> Checking if required setup is already done..."
  if [ ! -x "$(command -v ansible)" ]; then
    echo ">> Installing latest version of ansible"
    sudo apt update
    sudo apt install --yes ansible
    echo ">> Done."
  fi

  if [ ! -d "provisioning/roles" ]; then
    echo ">> Install Ansible Roles using ansible-galaxy"
    ansible-galaxy install -p ./provisioning/roles -r ./provisioning/requirements.yml
    echo ">> Done."
  fi
  echo ">> Finished."
}

provision() {
    local tags=$1

    tags=${tags:-all}
    local message=${tags:-full system}
    setup
    echo ">> Starting $message provisioning ..."
    ansible-playbook \
        --connection=local \
        -i localhost, \
        -i ./provisioning/inventory.yml \
        $inventory \
        -K --tags "$tags" provisioning/playbook.yml
    echo ">> Finished."
}

OPTS=`getopt -o hi: --long inventory:,help -- "$@"`
if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

eval set -- "$OPTS"

while true; do
    case "$1" in
        -i | --inventory )
            inventory="-i $2"
            shift 2 ;;
        -h | --help )
            usage
            exit
            shift ;;
        -- )
            shift
            break ;;
        * )
            break ;;
    esac
done

case "$1" in
    dotfiles )
        provision dotfiles
        ;;
    tooling )
        provision tooling
        ;;
    packages )
        provision packages
        ;;
    * )
        provision
        ;;
esac
