- name: configure colima plugins
  block:
  - name: Create docker plugins folder
    args:
      creates: "{{ ansible_env.HOME }}/.docker/cli-plugins"
    shell: |
      mkdir -p $HOME/.docker/cli-plugins

  - name: Create symlink for docker-compose
    args:
      creates: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-compose"
    shell: |
      ln -sfn /opt/homebrew/opt/docker-compose/bin/docker-compose $HOME/.docker/cli-plugins/docker-compose

  - name: Create symlink for docker-buildx
    args:
      creates: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-buildx"
    shell: |
      ln -sfn /opt/homebrew/opt/docker-buildx/bin/docker-buildx $HOME/.docker/cli-plugins/docker-buildx
