---
- name: Install nomad (by hashicorp)
  import_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: nomad
    url: "https://releases.hashicorp.com/nomad/{{ tooling.version.nomad }}/nomad_{{ tooling.version.nomad }}_linux_amd64.zip"
    version: "{{ tooling.version.nomad }}"
    unzip: true
