---
- name: Install packer (by hashicorp)
  include_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: packer
    url: "https://releases.hashicorp.com/packer/{{ tooling.version.packer }}/packer_{{ tooling.version.packer }}_linux_amd64.zip"
    version: "{{ tooling.version.packer }}"
    unzip: true
