---
- name: installs dependencies
  become: true
  apt:
    name:
      - gnupg2
      - pcscd
      - scdaemon

- name: Configure gpg.conf
  blockinfile:
    path: "{{ ansible_env.HOME }}/.gnupg/gpg.conf"
    # yamllint disable rule:line-length
    block: |
      personal-digest-preferences SHA256
      cert-digest-algo SHA256
      default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
      use-agent
    # yamllint enable rule:line-length
    create: true

- name: Configure gpg-agent
  lineinfile:
    path: "{{ ansible_env.HOME }}/.gnupg/gpg-agent.conf"
    line: enable-ssh-support
    create: true

- name: copy file
  copy:
    src: /etc/xdg/autostart/gnome-keyring-ssh.desktop
    dest: "{{ ansible_env.HOME }}/.config/autostart/gnome-keyring-ssh.desktop"
    remote_src: true
    force: false

- name: Disable gnome-keyring-ssh
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/autostart/gnome-keyring-ssh.desktop"
    line: Hidden=true
  register: gnome_keyring_ssh_disabled

- name: Restart gpg-agent
  command: "{{ item }}"
  loop:
    - gpg-connect-agent killagent /bye
    - gpg-connect-agent /bye
  when: gnome_keyring_ssh_disabled.changed
