#!/usr/bin/env bash
set -e

usage() {
    cat << USAGE
Usage:
    qypress [options] <host> <cypress command> [-- options for cypress]

Options:
    -h, --help          shows this message
    -m, --multisite     runs multisite fixtures
    -r, --remote        runs E2E Tests against cypress dashboard reports to locally checked out branch.
                        only works for RMS testsystems (Mailpit).

The package manager (pnpm or yarn) is detected from the lockfile in the
e2e-tests repository.

Example
    qypress -r "https://e2ehotfix.testing.modac.eu" run     runs all E2E on rms testsystem e2ehotfix and reports on the branch you have checked out locally
USAGE
}

OPTS=`getopt -o h --long help -o m --long multisite -o r --long remote -- "$@"`
if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

eval set -- "$OPTS"

integrationFolder="cypress/integration"
organizationalUnit="false"
remote="false"

while true; do
    case "$1" in
        -h | --help )
            usage
            exit 0
            shift ;;
        -m | --multisite )
            organizationalUnit="true"
            integrationFolder="cypress/integration_multisite"
            shift ;;
        -r | --remote )
            remote="true"
            shift ;;
        -- )
            shift
            break ;;
        * )
            break ;;
    esac
done

shift $(expr $OPTIND - 1 )
host=$1
shift

pushd "$REPOS_DIRECTORY/QwikiContrib/e2e-tests"

remainingArgs=$@

if [[ -f "pnpm-lock.yaml" ]]; then
    installCommand=(pnpm install)
    cypressCommand=(pnpm exec cypress)
elif [[ -f "yarn.lock" ]]; then
    installCommand=(yarn install)
    cypressCommand=(yarn cypress)
else
    echo "Neither pnpm-lock.yaml nor yarn.lock found in $PWD" >&2
    exit 1
fi

mailPitUrl="$host:8025"
if [[ "$host" == *qluster.localhost ]]; then
    mailPitUrl="https://mailpit.qluster.localhost"
    oidcMockAuthorizeUrl="https://oidc.qluster.localhost/connect/authorize"
    oidcMockTokenUrl="http://qwiki-local-oidc.default.svc.cluster.local/connect/token"
fi

"${installCommand[@]}"
if [[ "$remote" == "true" ]];
then
    if [ -z "$CYPRESS_RECORD_KEY" ]; then
        echo "Missing CYPRESS_RECORD_KEY environment variable"
        exit 1
    fi
    if [ -z "$CYPRESS_PROJECT_ID" ]; then
        echo "Missing CYPRESS_PROJECT_ID environment variable"
        exit 1
    fi

    mailPitUrl=$(sed "s/^https:\/\//http:\/\/mailpit./g" <<< $host)

    LANG="en_EN.UTF-8" \
    CYPRESS_baseUrl=$host/ \
    CYPRESS_mailPitUrl=$mailPitUrl \
    CYPRESS_oidcMockAuthorizeUrl=$oidcMockAuthorizeUrl \
    CYPRESS_oidcMockTokenUrl=$oidcMockTokenUrl \
    CYPRESS_integrationFolder=$integrationFolder \
    CYPRESS_organizationalUnit=$organizationalUnit \
    CYPRESS_PROJECT_ID=$CYPRESS_PROJECT_ID \
        "${cypressCommand[@]}" $@ --record --key $CYPRESS_RECORD_KEY

else

    LANG="en_EN.UTF-8" \
    CYPRESS_baseUrl=$host/ \
    CYPRESS_mailPitUrl=$mailPitUrl \
    CYPRESS_oidcMockAuthorizeUrl=$oidcMockAuthorizeUrl \
    CYPRESS_oidcMockTokenUrl=$oidcMockTokenUrl \
    CYPRESS_integrationFolder=$integrationFolder \
    CYPRESS_organizationalUnit=$organizationalUnit \
        "${cypressCommand[@]}" $@
fi

popd
