#!/usr/bin/env bash
set -e


if [[ ! "$(command -v curl)" && "$(uname -s)" = "Linux"* ]]; then
    echo "Installing curl"
    sudo apt update
    sudo apt install -y curl
fi

if [ -z $( which devbox ) ]; then
    echo "Installing devbox"
    curl -fsSL https://get.jetify.com/devbox | bash
fi

if [ -z "$( cat $HOME/.bashrc | grep '/.bash_completions/' )" ]; then
    cat <<EOT >> $HOME/.bashrc
if [ -d ~/.bash_completions ]; then
    for completion in \$(find \$HOME/.bash_completions/ -maxdepth 1 -type f); do
        . \$completion
    done
fi
EOT
fi

env_path="$HOME/.env"
[[ ! -f "$env_path" ]] && touch "$env_path"

if [ ! -f $HOME/.bash_completions/devbox.sh ]; then
    mkdir -p $HOME/.bash_completions
    devbox completion bash > $HOME/.bash_completions/devbox.sh
fi

if [ -z "$( cat $HOME/.bashrc | grep 'devbox global shellenv --init-hook' )" ]; then
    echo 'eval "$(devbox global shellenv --init-hook)"' >> $HOME/.bashrc
fi

base_path=$( dirname $(realpath "$0") )
default_devbox_dir="$HOME/.local/share/devbox/global/default"
global_devbox="$default_devbox_dir/devbox.json"

echo $base_path
[ ! -d $default_devbox_dir ] && mkdir -p $default_devbox_dir
[ ! -f $global_devbox ] && sed "s#{base_path}#$base_path#g;s#{env_path}#$env_path#" "$base_path/templates/devbox.json" > $global_devbox

devbox global update
