#!/usr/bin/env bash
set -e

# renovate: datasource=github-releases depName=python-poetry/poetry
export POETRY_VERSION=2.0.1


export QWIKI_DEVELOPMENT_ROOT_CA="$HOME/.local/share/mkcert"


if [[ "$(uname -s)" = "Linux"* ]]; then
    export ARCH="Ubuntu"
    export IS_UBUNTU=true
else
    export export ARCH="Darwin"
    export export IS_DARWIN=true
fi

function run() {
    local module=$1

    echo "Running $module"
    if [ -f "provision-scripts/$ARCH/$module.bash" ]; then
        bash ./provision-scripts/$ARCH/$module.bash
    elif [ -f "provision-scripts/$module.bash" ]; then
        bash ./provision-scripts/$module.bash
    else
        echo "Module '$module.bash' not found"
        exit 1
    fi
}

eval "$(devbox global shellenv --init-hook)"

modules="
packages
setup-envs
asdf-packages
asdf
kubectl-krew
setup-k8s-cluster
poetry
k3s-network
node
certificates
install-modac-shell-helper
docker
docker-packages
"

current=$(dirname "$(realpath $0)")
pushd $current
for module in $modules; do
    run $module
done
popd
