#!/usr/bin/env bash
set -e

# renovate: datasource=github-releases depName=python-poetry/poetry
export POETRY_VERSION=2.0.1

function run() {
    local module=$1

    if [ -f "provision-scripts/$ARCH/$module.bash" ]; then
        bash ./provision-scripts/$ARCH/$module.bash
    elif [ -f "provision-scripts/$module.bash" ]; then
        bash ./provision-scripts/$module.bash
    else
        echo "Module '$module.bash' not found"
        exit 1
    fi
}

if [[ "$(uname -s)" = "Linux"* ]]; then
    export ARCH="Ubuntu"
    export IS_UBUNTU=true
else
    export export ARCH="Darwin"
    export export IS_DARWIN=true
fi

current=$(dirname "$(realpath $0)")
pushd $current
for module in "asdf-packages" "asdf" "kubectl-krew" "docker-packages" "docker" "poetry"; do
    run $module
done
popd
