---
- name: Installs and configures Docker
  homebrew_cask:
    name: docker
    accept_external_apps: true
    state: installed

- name: Install docker python package
  ansible.builtin.pip:
    name: docker

- name: Create custom network bridge for k8s operations.
  include_tasks:
      file: tasks/docker/docker_create_k8s_bridge.yml
