---
- name: Install skaffold (by google)
  include_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: skaffold
    url: "https://storage.googleapis.com/skaffold/releases/{{ tooling.version.skaffold }}/skaffold-darwin-{{ machine_architecture }}"
    version: "{{ tooling.version.skaffold }}"
    unzip: false
