---
- name: Install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ tooling.version.nvm }}/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install all required node versions
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm install {{ item }}
  loop: "{{ tooling.version.node.installed }}"

- name: Set default node version
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm use {{ tooling.version.node.default }}
