---

- name: Install packages on Debian.
  become: true
  block:
    - name: Ensure python-apt is installed.
      apt:
        name: "python3-apt"

    - name: Ensure common packages are installed.
      apt:
        name: "{{ all_packages_debian }}"

    - name: Update restic
      command: restic self-update
  when: is_ubuntu

- name: Install packages on Darwin.
  block:
    - name: Ensure common packages are installed.
      homebrew:
        name: "{{ package }}"
      loop: "{{ all_packages_darwin }}"
      loop_control:
        loop_var: package
  when: is_macos
