---
- name: Remove packages on Debian.
  become: true
  block:
    - name: Ensure unwanted packages are removed.
      apt:
        name: "{{ all_remove_packages_debian }}"
        state: absent
  when: is_ubuntu

- name: Remove packages on Darwin.
  block:
    - name: Ensure unwanted packages are removed.
      homebrew:
        name: "{{ package }}"
        state: absent
      loop: "{{ all_remove_packages_darwin }}"
      loop_control:
        loop_var: package
  when: is_macos
