---

- name: Accept github as known hosts
  become: true
  shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts

- name: Clone/Update modac-bash
  git:
    repo: "git@github.com:modell-aachen/modac-bash"
    dest: "{{ ansible_env.HOME }}/.modac-bash"

- name: Create Q.wiki repo
  file:
    path: "item"
    state: directory
  loop:
    - "{{ all_env['REPOS_DIRECTORY'] }}"
    - "{{ all_env['PROVISIONER_DIRECTORY'] }}"
