---

- name: Accept github as known hosts
  become: true
  shell: ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts

- name: Clone/Update modac-bash
  git:
    repo: "git@github.com:modell-aachen/modac-bash"
    dest: "{{ ansible_env.HOME }}/.modac-bash"

- name: Create Q.wiki repo
  file:
    path: "item"
    state: directory
  loop:
    - "{{ all_env['REPOS_DIRECTORY'] }}"
    - "{{ all_env['PROVISIONER_DIRECTORY'] }}"

- name: Configure shell rc for modac-bash
  block:
    - name: Check if .bashrc exists
      stat:
        path: "{{ ansible_env.HOME }}/.bashrc"
      register: bashrc

    - name: Ensure modac-bash is sourced in .bashrc, iff .bashrc exists
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ item }}"
      loop:
        - "[ -f $HOME/.modac-bash/bashrc.sh ] && source $HOME/.modac-bash/bashrc.sh"
        - "[ -f $HOME/.env ] && source $HOME/.env"
      when: bashrc.stat is defined and bashrc.stat.exists

    - name: Check if .zshrc exists
      stat:
        path: "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc

    - name: Ensure modac-bash is sourced in .zshrc, iff .zshrc exists
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: "{{ item }}"
      loop:
        - "[ -f $HOME/.modac-bash/bashrc.sh ] && source $HOME/.modac-bash/bashrc.sh"
        - "[ -f $HOME/.env ] && source $HOME/.env"
      when: zshrc.stat is defined and zshrc.stat.exists
  when: configure_shell_rc
