---
- stat:
    path: "{{ all_env['QWIKI_DEVELOPMENT_ROOT_CA'] }}/rootCA.pem"
  register: root_ca_folder

- name: Create local CA
  command: mkcert -install
  environment:
    CAROOT: "{{ all_env['QWIKI_DEVELOPMENT_ROOT_CA'] }}"
  when: not root_ca_folder.stat.exists

- name: Create certificates
  include_tasks: tasks/certificates/generate_certificate.yml
  vars:
    host: "{{ item.host }}"
    location: "{{ item.location }}"
  loop: "{{ dev.certificates }}"
