---
- name: Install flux CLI
  shell: |
    curl -s https://fluxcd.io/install.sh | sudo FLUX_VERSION="{{tooling.version.docker.compose}}" bash
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/flux2"
