---
- name: Install helm
  include_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: helm
    url: "https://github.com/helm/helm/releases/download/{{ tooling.version.helm }}/helm-{{ tooling.version.helm }}-{{ ansible_system | lower }}-{{ machine_architecture }}.tar.gz"
    version: "{{ tooling.version.helm }}"
    unzip: true
    extra_opts:
      - "--strip-components=1"
