---
- name: Install kubectl
  include_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: kubectl
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ tooling.version.kubectl }}/bin/{{ ansible_system | lower }}/{{ machine_architecture }}/kubectl"
    version: "{{ tooling.version.kubectl }}"
    unzip: false

- name: Install Krew for Kubectl
  include_tasks:
    file: tasks/install/general/krew.yml

- name: Install krew plugins for Kubernetes (kubectl)
  include_tasks:
    file: tasks/install/general/krew_plugins.yml
