---
- name: Install nomad (by hashicorp)
  include_tasks:
    file: tasks/install/_install_versioned_binary.yml
  vars:
    name: nomad
    url: "https://releases.hashicorp.com/nomad/{{ tooling.version.nomad }}/nomad_{{ tooling.version.nomad }}_{{ ansible_system | lower }}_{{ machine_architecture }}.zip"
    version: "{{ tooling.version.nomad }}"
    unzip: true
