- name: Install nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ tooling.version.nvm }}/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install all required node versions
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm install {{ item }}
  loop: "{{ tooling.version.node.modern + tooling.version.node.legacy }}"
  args:
    executable: /bin/bash

- name: Install yarn for legacy node versions
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm use {{ item }}
    npm install --global yarn
  loop: "{{ tooling.version.node.legacy }}"
  args:
    executable: /bin/bash

- name: Install latest yarn for modern node versions
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm use {{ item }}
    npm uninstall -g yarn
    corepack enable
    corepack install -g yarn@latest
  loop: "{{ tooling.version.node.modern }}"
  args:
    executable: /bin/bash

- name: Set default node version
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm alias default {{ tooling.version.node.default }}
    nvm use {{ tooling.version.node.default }}
  args:
    executable: /bin/bash
