---
- name: Install poetry
  shell: |
    curl -sSL https://install.python-poetry.org | python3 - --version {{ tooling.version.poetry }}
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/poetry"
    
